#!/bin/bash
cd ${0%/*} || exit 1    # run from this directory

if [ ! -f $CUDA_BIN_DIR/nvcc ]
then
    echo "No nvcc - CUDA not available."
    exit 0
fi

if [ -n "$CUDA_IGNORE" ]
then
    echo "Found nvcc but \$CUDA_IGNORE set -- not  enabling CUDA support."
    exit 0
else
    echo "Found nvcc  --  enabling CUDA support."
fi

if [ ! -f "$ISPM_DIR"/libispm0-pic.a ]
then
    echo "ISPM library not available"
    exit 0
fi

FOAM_VERSION=$( (IFS=. read a b c; echo $[$a*100 + $b]) <<<$WM_PROJECT_VERSION)

export FOAM_VERSION

wmake libso

unset  FOAM_VERSION


# ----------------------------------------------------------------- end-of-file
